color: null
fieldLayouts:
  8658c3c4-b02f-4a41-b2c1-52b4ad80f6d3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T10:33:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4a5fe670-1dcc-47ad-995c-d9fb83c635bc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T10:35:44+00:00'
            elementCondition: null
            fieldUid: e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8 # Subtext
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47688ddf-c058-4336-993b-a82f433ce580
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T10:35:44+00:00'
            elementCondition: null
            fieldUid: 35c35080-108d-485f-925f-407a5ab65a22 # Cover
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e584fe90-a158-4487-9e87-b808cefa5f28
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 142e8232-3f48-45a1-9a34-54c39f2da9c9
        userCondition: null
handle: categories
hasTitleField: true
icon: ''
name: Categories
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
